# Generated by Django 4.2.5 on 2023-09-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_roll', models.IntegerField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
