# Generated by Django 4.2.5 on 2023-09-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
