# Generated by Django 4.2.5 on 2023-09-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='city',
            field=models.CharField(blank=True, choices=[('jaipur', 'Jaipur'), ('udaipur', 'Udaipur'), ('kota', 'Kota'), ('jodhpur', 'Jodhpur')], max_length=50, null=True),
        ),
    ]
