# Generated by Django 4.2.5 on 2023-10-03 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_remove_add_to_cart_user_add_to_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='user',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='product',
            field=models.ManyToManyField(to='myapp.product'),
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
